### ISSUE TITLE
RunTestDeflate

### ISSUE THREAD

**Issue by gju06051** [HEAP-Lab-VT/ASIC-DEFLATE-for-memory#4]
I also have error in ./gradlew runTestDeflate with no any change.

-------------------------------Error Log-------------------------------
root@xxxxxxxxx:~/mnt/ASIC-DEFLATE-for-memory# gradlew runTestDeflate

> Task :linkTestDeflate FAILED
/usr/bin/ld: /root/mnt/ASIC-DEFLATE-for-memory/build/verilated.o: in function `VerilatedContext::threadPoolp()':
verilated.cpp:(.text+0x286d): undefined reference to `VlThreadPool::VlThreadPool(VerilatedContext*, unsigned int)'
/usr/bin/ld: /root/mnt/ASIC-DEFLATE-for-memory/build/verilated.o: in function `VerilatedContext::threadPoolpOnClone()':
verilated.cpp:(.text+0xb23d): undefined reference to `VlThreadPool::VlThreadPool(VerilatedContext*, unsigned int)'
collect2: error: ld returned 1 exit status

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':linkTestDeflate'.
> Process 'command 'g++'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
13 actionable tasks: 1 executed, 12 up-to-date

-------------------------------Environment -------------------------------

g++ and verilator setting is under below

g++ version
(Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Verilator version
Verilator 5.031 devel rev UNKNOWN.REV

-------------------------------Comment-------------------------------
I downloaded verilator on github(https://github.com/verilator/verilator?tab=readme-ov-file) recent version and finished example test of verilator following this document(https://verilator.org/guide/latest/install.html). But maybe not support some component in recent version of verilator like erilatedContext::threadPoolp(), so the error occur.

I want to know your version of verilator or other solution to simple run.

Thank you for pay attention!

**Comment by gju06051** [comment]
This is terminal print of g++ -v command


`Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.2' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-9QDOt0/gcc-9-9.4.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.2)`

**Comment by gju06051** [comment]
@dbear496

**Comment by dbear496** [comment]
It's been a while since I've touched this project, but I recall it building fine with Verilator 5.002. Potentially if you try using an older version of Verilator that may help. My Verilator code makes no explicit use of multithreading, so it's not obvious to me why you would be getting an error about thread-pool stuff.

**Comment by gju06051** [comment]
Thanks you!
I've checked out running with Verilator-4.210 worked well. (Refer previous closed issue)
